# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_status_id', models.BigIntegerField()),
                ('status_content', models.CharField(help_text='140 + 2x15 + 15error + 1error', max_length=186)),
                ('bot_has_issued_challege', models.BooleanField(default=False, help_text='Tweet of So @playerone wants to settle this by #RockPaperScissors')),
                ('instigator_rpc', models.CharField(choices=[('N', 'None'), ('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], default='N', max_length=1)),
                ('confederate_rpc', models.CharField(choices=[('N', 'None'), ('R', 'Rock'), ('P', 'Paper'), ('S', 'Scissors')], default='N', max_length=1)),
                ('draws', models.IntegerField(default=0)),
                ('settled', models.BooleanField(default=False)),
                ('instigator_won', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(help_text='screen_name', max_length=15)),
                ('optout', models.BooleanField(default=True)),
                ('retweets', models.BooleanField(default=False)),
                ('following', models.BooleanField(default=False)),
                ('followed_by', models.BooleanField(default=False)),
                ('premium', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_confederate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_confederate', to='bot.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_instigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_instigator', to='bot.Player'),
        ),
    ]
