# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='rate_name', max_length=255, unique=True)),
                ('per_fifteen_minute', models.IntegerField(default=40, help_text='True Value')),
                ('current_tokens', models.IntegerField(default=0, help_text='Max is half of api_rate_per_fifteen_minute')),
                ('last_token_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
