# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='per_fifteen_minute',
            new_name='per_hour',
        ),
        migrations.AlterField(
            model_name='rate',
            name='current_tokens',
            field=models.IntegerField(default=0, help_text='Max is half of api_rate per_hour'),
        ),
    ]
